buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Povýšeno na 8.7.3 pro zajištění kompatibility s Gradle 9
        classpath "com.android.tools.build:gradle:8.7.3"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.25"
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}
